### ISSUE TITLE
Why middleware for a high-performance framework?

### ISSUE THREAD

**Issue by aquapi** [Im-Beast/hydra#1]
Middleware has poor performance compared to plain routing.

This is my experience when working with Stric.

**Comment by aquapi** [comment]
Everytime I see a high-performance framework, I always know that there is at least something not going in the right direction. (Don't use RegExp routes)

**Comment by Im-Beast** [comment]
I'm not sure you even tried Hydra – it doesn't use `RegExp` for routing and I'm not sure what do you mean by "plain routing" either.
